# Generated by Django 6.0.4 on 2026-04-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
